export const FETCHING_FRIENDS_REQUEST = 'FETCHING_FRIENDS_REQUEST';
export const FETCHING_FRIENDS_SUCCESS = 'FETCHING_FRIENDS_SUCCESS';
export const FETCHING_FRIENDS_FAILURE = 'FETCHING_FRIENDS_FAILURE';
